name: CD Pipeline

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Push a Docker Image"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: sudo docker pull spurthi04/bikeshare-fastapi2:latest 
      - name: Delete Old Docker Container
        run: sudo docker rm -f bikeshare-fastapi2-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name=bikeshare-fastapi2-container spurthi04/bikeshare-fastapi2:latest
